CREATE TABLE "SCOTT"."ORDERS" 
   (	"ORDER_ID" NUMBER(*,0), 
	"QUANTITY" NUMBER(*,0), 
	"ORDER_DATE" DATE, 
	"CUSTOMER_ID" NUMBER(*,0)
   );
/

CREATE TABLE "SCOTT"."CUSTOMERS" 
   (	"CUSTOMER_ID" NUMBER(*,0), 
	"NAME" VARCHAR2(20 BYTE)
   ) ;
/

REM INSERTING into SCOTT.CUSTOMERS
SET DEFINE OFF;
Insert into SCOTT.CUSTOMERS (CUSTOMER_ID,NAME) values (1,'Comp_A');
Insert into SCOTT.CUSTOMERS (CUSTOMER_ID,NAME) values (2,'Comp_B');
Insert into SCOTT.CUSTOMERS (CUSTOMER_ID,NAME) values (3,'Comp_C');
Insert into SCOTT.CUSTOMERS (CUSTOMER_ID,NAME) values (4,'Comp_D');
Insert into SCOTT.CUSTOMERS (CUSTOMER_ID,NAME) values (5,'Comp_E');

REM INSERTING into SCOTT.ORDERS
SET DEFINE OFF;
Insert into SCOTT.ORDERS (ORDER_ID,QUANTITY,ORDER_DATE,CUSTOMER_ID) values (1,1,to_date('01-JUN-17','DD-MON-RR'),1);
Insert into SCOTT.ORDERS (ORDER_ID,QUANTITY,ORDER_DATE,CUSTOMER_ID) values (2,2,to_date('01-JUN-17','DD-MON-RR'),1);
Insert into SCOTT.ORDERS (ORDER_ID,QUANTITY,ORDER_DATE,CUSTOMER_ID) values (3,5,to_date('02-JUN-17','DD-MON-RR'),1);
Insert into SCOTT.ORDERS (ORDER_ID,QUANTITY,ORDER_DATE,CUSTOMER_ID) values (4,10,to_date('03-JUN-17','DD-MON-RR'),1);
Insert into SCOTT.ORDERS (ORDER_ID,QUANTITY,ORDER_DATE,CUSTOMER_ID) values (5,null,to_date('04-JUN-17','DD-MON-RR'),1);
Insert into SCOTT.ORDERS (ORDER_ID,QUANTITY,ORDER_DATE,CUSTOMER_ID) values (6,1,to_date('01-JUN-17','DD-MON-RR'),2);
Insert into SCOTT.ORDERS (ORDER_ID,QUANTITY,ORDER_DATE,CUSTOMER_ID) values (7,10,to_date('02-JUN-17','DD-MON-RR'),2);
Insert into SCOTT.ORDERS (ORDER_ID,QUANTITY,ORDER_DATE,CUSTOMER_ID) values (8,null,to_date('03-JUN-17','DD-MON-RR'),2);
Insert into SCOTT.ORDERS (ORDER_ID,QUANTITY,ORDER_DATE,CUSTOMER_ID) values (9,5,to_date('03-JUN-17','DD-MON-RR'),2);
Insert into SCOTT.ORDERS (ORDER_ID,QUANTITY,ORDER_DATE,CUSTOMER_ID) values (10,10,to_date('01-JUN-17','DD-MON-RR'),3);
Insert into SCOTT.ORDERS (ORDER_ID,QUANTITY,ORDER_DATE,CUSTOMER_ID) values (11,20,to_date('01-JUN-17','DD-MON-RR'),3);
Insert into SCOTT.ORDERS (ORDER_ID,QUANTITY,ORDER_DATE,CUSTOMER_ID) values (12,1,to_date('06-JUN-17','DD-MON-RR'),3);
Insert into SCOTT.ORDERS (ORDER_ID,QUANTITY,ORDER_DATE,CUSTOMER_ID) values (14,2,to_date('05-JUN-17','DD-MON-RR'),4);
Insert into SCOTT.ORDERS (ORDER_ID,QUANTITY,ORDER_DATE,CUSTOMER_ID) values (16,1,to_date('01-JUN-17','DD-MON-RR'),5);
Insert into SCOTT.ORDERS (ORDER_ID,QUANTITY,ORDER_DATE,CUSTOMER_ID) values (17,null,to_date('02-JUN-17','DD-MON-RR'),5);


commit;
/

